export const restaurantData = {
  restaurants: [
    {
      info: {
        id: "11091",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Attapur",
        areaName: "Attapur",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 29,
          lastMileTravel: 1.4,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "1.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-04 04:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "ITEMS",
          subHeader: "AT ₹189",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/pizza-hut-attapur-hyderabad-11091",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "360967",
        name: "Wow! Momo",
        cloudinaryImageId: "64fd45fd9f44c1737bc446e470bed666",
        locality: "Vishwa Bhawan",
        areaName: "Himayath Nagar",
        costForTwo: "₹300 for two",
        cuisines: [
          "Tibetan",
          "Healthy Food",
          "Asian",
          "Chinese",
          "Snacks",
          "Continental",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.3,
        parentId: "1776",
        avgRatingString: "4.3",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 41,
          lastMileTravel: 8.2,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "8.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-04 01:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "Rxawards/_CATEGORY-Chinese.png",
              description: "Delivery!",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "Delivery!",
                    imageId: "Rxawards/_CATEGORY-Chinese.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/wow-momo-vishwa-bhawan-himayath-nagar-hyderabad-360967",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "659667",
        name: "Barbeque Nation",
        cloudinaryImageId: "8b3a3993448aeba5ee8e6f63be94bb60",
        locality: "COMMERCIAL CENTRE",
        areaName: "Attapur",
        costForTwo: "₹600 for two",
        cuisines: [
          "North Indian",
          "Barbecue",
          "Biryani",
          "Kebabs",
          "Mughlai",
          "Desserts",
        ],
        avgRating: 3.7,
        parentId: "2438",
        avgRatingString: "3.7",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 40,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-03 23:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/barbeque-nation-commercial-centre-attapur-hyderabad-659667",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "624472",
        name: "Leon's - Burgers & Wings (Leon Grill)",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/5/2/4c1e29e2-fecf-41b6-8b21-5a58338247fe_624472.jpg",
        locality: "Himayath Nagar",
        areaName: "Himayat Nagar",
        costForTwo: "₹300 for two",
        cuisines: [
          "Burgers",
          "American",
          "Turkish",
          "Portuguese",
          "Continental",
          "Snacks",
        ],
        avgRating: 4.3,
        parentId: "371281",
        avgRatingString: "4.3",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 36,
          lastMileTravel: 7.9,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "7.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-04 03:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/leons-burgers-and-wings-leon-grill-himayath-nagar-himayat-nagar-hyderabad-624472",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "355750",
        name: "Grameen Kulfi",
        cloudinaryImageId: "dkcduodu7fuqn5lqn8f2",
        locality: "Hakeempet",
        areaName: "Toli Chowki",
        costForTwo: "₹120 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.5,
        veg: true,
        parentId: "12175",
        avgRatingString: "4.5",
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 5.7,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "5.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-04 00:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "EVERY ITEM",
          subHeader: "@ ₹99",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/grameen-kulfi-hakeempet-toli-chowki-hyderabad-355750",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "262087",
        name: "Imperial Multi-Cusine Restaurant",
        cloudinaryImageId: "rqlwvsmzcfxbg9u6ajgm",
        locality: "Banjara Hills",
        areaName: "Redhills",
        costForTwo: "₹400 for two",
        cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
        avgRating: 4.2,
        parentId: "19254",
        avgRatingString: "4.2",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 5.5,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "5.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-03 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/imperial-multi-cusine-restaurant-banjara-hills-redhills-hyderabad-262087",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "237054",
        name: "Cafe Bahar since 1973",
        cloudinaryImageId: "yrycuz88yy7lm2qbsdv6",
        locality: "Basheerbagh",
        areaName: "Basheer Bagh",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
        avgRating: 4.3,
        parentId: "316607",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 31,
          lastMileTravel: 7.5,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "7.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-03 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/cafe-bahar-since-1973-basheerbagh-basheer-bagh-hyderabad-237054",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "312800",
        name: "Hilton Restaurant (Hillstar)",
        cloudinaryImageId: "ne98mz09ikwfpz3ndws6",
        locality: "Khairatabad",
        areaName: "Khairatabad",
        costForTwo: "₹300 for two",
        cuisines: ["Chinese", "Biryani"],
        avgRating: 4.3,
        parentId: "19233",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 32,
          lastMileTravel: 6.3,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-07-04 02:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-8b9ec9fe-27a7-42ee-881f-2b4e178c036c",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/hilton-restaurant-hillstar-khairatabad-hyderabad-312800",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "255655",
        name: "Cake & Cream",
        cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
        areaName: "Jairaj Nagar",
        costForTwo: "₹200 for two",
        cuisines: ["Bakery", "Hot-dog", "pastery", "Cake", "Thick- shake"],
        avgRating: 4.3,
        veg: true,
        parentId: "54670",
        avgRatingString: "4",
        totalRatingsString: "20+",
      },
    },
    {
      info: {
        id: "350363",
        name: "Haldiram's Sweets and Namkeen",
        cloudinaryImageId: "25c3a7d394d6c5556b134385f7d665b0",
        avgRating: 4.6,
        veg: true,
        cuisines: [
          "North Indian",
          "South Indian",
          "Chinese",
          "Pizzas",
          "Fast Food",
        ],
        parentId: "391465",
        avgRatingString: "4.6",
        totalRatingsString: "100+",
      },
    },
    {
      info: {
        id: "154891",
        name: "Rasraj Restaurant",
        cloudinaryImageId: "egbr63ulc8h1zgliivd8",
        locality: "Civil Line",
        areaName: "Civil Lines",
        costForTwo: "₹250 for two",
        cuisines: [
          "North Indian",
          "South Indian",
          "Street Food",
          "Chinese",
          "Pizzas",
          "Fast Food",
        ],
        avgRating: 4.2,
      },
    },
    {
      info: {
        id: "745961",
        name: "Balaji Restaurant",
        cloudinaryImageId: "b8672fe52944c3599ea324d99d608300",
        locality: "Sai Rubber Stamp",
        areaName: "Jairaj Nagar",
        costForTwo: "₹149 for two",
        cuisines: ["South Indian", "North Indian"],
        avgRating: 4.8,
        veg: true,
      },
    },
    {
      info: {
        id: "798745",
        name: "Friends Restaurant",
        cloudinaryImageId: "b14cd9fc40129fcfb97aa7e621719d07",
        locality: "Gayatri Nagar",
        areaName: "Jairaj Nagar",
        costForTwo: "₹150 for two",
        cuisines: ["North Indian", "Chinese", "Biryani", "Tandoor", "Kebabs"],
        avgRating: 4.2,
        parentId: "84308",
      },
    },
    {
      info: {
        id: "314737",
        name: "RASOI the KITCHEN",
        cloudinaryImageId: "yjymo9nhyn7rhvafsrd3",
        locality: "Sriram Chowk",
        areaName: "Bazar Ward",
        costForTwo: "₹200 for two",
        cuisines: ["North Indian", "Maharashtrian", "Chinese", "Thalis"],
        avgRating: 3.9,
        parentId: "167341",
      },
    },
    {
      info: {
        id: "201454",
        name: "Morsels restaurants",
        cloudinaryImageId: "aafe71251ef5328784652dc838cd91f3",
        locality: "Bazar Ward",
        areaName: "Chandrapur Locality",
        costForTwo: "₹300 for two",
        cuisines: ["North Indian", "South Indian"],
        avgRating: 3.2,
        veg: true,
        parentId: "139266",
        avgRatingString: "4.2",
      },
    },
    {
      info: {
        id: "266124",
        name: "Trimurti Restaurant",
        cloudinaryImageId: "8135c0066b06e2925c66930be4e9ffb5",
        locality: "Bazar Ward",
        areaName: "Chandrapur Locality",
        costForTwo: "₹150 for two",
        cuisines: ["Desserts"],
        avgRating: 3.9,
        veg: true,
        parentId: "217751",
        avgRatingString: "4.4",
      },
    },
    {
      info: {
        id: "509254",
        name: "Saha Restaurant",
        cloudinaryImageId: "z1ez4uc9idul2uj2v87g",
        areaName: "Jairaj Nagar",
        costForTwo: "₹300 for two",
        cuisines: ["North Indian", "Biryani", "Thalis", "Beverages"],
        avgRating: 3.7,
        parentId: "174585",
        avgRatingString: "3.7",
      },
    },
  ],
};
